---
- name: Converge
  hosts: all
  tasks:
    - name: Uninstall NGINX
      include_role:
        name: ansible-role-nginx
      vars:
        nginx_setup: uninstall
        nginx_type: plus
        nginx_setup_license: false
