---
- name: (Amazon Linux/CentOS/RHEL) {{ (nginx_setup == 'uninstall') | ternary('Remove', 'Configure') }} NGINX repository
  yum_repository:
    name: nginx
    baseurl: "{{ nginx_repository |
              default(lookup('vars', 'nginx_default_repository_' + ((ansible_facts['distribution'] == 'Amazon') | ternary('amazon', 'redhat')))) }}"
    description: NGINX Repository
    enabled: true
    gpgcheck: true
    mode: 0644
    module_hotfixes: true
    state: "{{ (nginx_state == 'uninstall') | ternary('absent', 'present') }}"
  when: nginx_manage_repo | bool

- name: (Amazon Linux/CentOS/RHEL) {{ nginx_setup | capitalize }} NGINX
  yum:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
    update_cache: true
    allow_downgrade: true
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
