---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      package:
        name: nginx
        state: absent
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
